import { KitchenProduct } from "./types";

export const kitchenProducts: KitchenProduct[] = [
    // Cabinets
    { id: "kp_001", sku: "CAB-W3024", name: "30\" x 24\" Wall Cabinet", brand: "Castile Kitchens", category: "Cabinet", style: "Shaker", finish: "Antique White", unitPrice: 189.00, unit: "each", description: "30 inch wide x 24 inch tall wall cabinet, solid wood face frame, soft-close hinges", leadTimeDays: 14, inStock: true },
    { id: "kp_002", sku: "CAB-W3630", name: "36\" x 30\" Wall Cabinet", brand: "Castile Kitchens", category: "Cabinet", style: "Shaker", finish: "Antique White", unitPrice: 229.00, unit: "each", description: "36 inch wide x 30 inch tall wall cabinet, soft-close hinges", leadTimeDays: 14, inStock: true },
    { id: "kp_003", sku: "CAB-B36", name: "36\" Base Cabinet", brand: "Castile Kitchens", category: "Cabinet", style: "Shaker", finish: "Antique White", unitPrice: 279.00, unit: "each", description: "36 inch wide base cabinet with adjustable shelf and drawer", leadTimeDays: 14, inStock: true },
    { id: "kp_004", sku: "CAB-B24", name: "24\" Base Cabinet", brand: "Castile Kitchens", category: "Cabinet", style: "Shaker", finish: "Antique White", unitPrice: 219.00, unit: "each", description: "24 inch wide base cabinet with adjustable shelf", leadTimeDays: 14, inStock: true },
    { id: "kp_005", sku: "CAB-B18", name: "18\" Base Cabinet", brand: "Castile Kitchens", category: "Cabinet", style: "Shaker", finish: "Antique White", unitPrice: 179.00, unit: "each", description: "18 inch wide base cabinet with drawer", leadTimeDays: 14, inStock: true },
    { id: "kp_006", sku: "CAB-T30", name: "30\" Tall Cabinet", brand: "Castile Kitchens", category: "Cabinet", style: "Shaker", finish: "Espresso", unitPrice: 399.00, unit: "each", description: "84 inch tall pantry cabinet, 30 inch wide, 4 adjustable shelves", leadTimeDays: 21, inStock: false },
    { id: "kp_007", sku: "CAB-W3024-GR", name: "30\" x 24\" Wall Cabinet - Gray", brand: "Castile Kitchens", category: "Cabinet", style: "Shaker", finish: "Graphite Gray", unitPrice: 199.00, unit: "each", description: "30 inch wide x 24 inch tall wall cabinet in Graphite Gray finish", leadTimeDays: 21, inStock: true },
    { id: "kp_008", sku: "CAB-ISLAND-72", name: "72\" Kitchen Island", brand: "Castile Kitchens", category: "Cabinet", style: "Contemporary", finish: "Two-Tone", unitPrice: 1290.00, unit: "each", description: "72 inch kitchen island with seating overhang, 4 drawers, 4 doors", leadTimeDays: 28, inStock: false },
    { id: "kp_009", sku: "CAB-B30-DRAWER", name: "30\" Drawer Base", brand: "Castile Kitchens", category: "Cabinet", style: "Shaker", finish: "Antique White", unitPrice: 349.00, unit: "each", description: "30 inch wide full-height drawer base, 3 drawers, soft-close", leadTimeDays: 14, inStock: true },
    { id: "kp_010", sku: "CAB-CORNER-LAZY", name: "Corner Cabinet w/ Lazy Susan", brand: "Castile Kitchens", category: "Cabinet", style: "Shaker", finish: "Antique White", unitPrice: 459.00, unit: "each", description: "Blind corner cabinet with full-circle lazy susan", leadTimeDays: 21, inStock: true },
    // Countertops
    { id: "kp_011", sku: "CTR-QTZ-CALACATTA", name: "Calacatta Quartz Countertop", brand: "Castile Stone", category: "Countertop", style: "Modern", finish: "Polished", unitPrice: 85.00, unit: "sq ft", description: "Calacatta white quartz with gold veining, 3cm thick, polished finish", leadTimeDays: 10, inStock: true },
    { id: "kp_012", sku: "CTR-QTZ-CARRARA", name: "Carrara Quartz Countertop", brand: "Castile Stone", category: "Countertop", style: "Classic", finish: "Polished", unitPrice: 78.00, unit: "sq ft", description: "Carrara white quartz, subtle gray veining, 3cm thick", leadTimeDays: 10, inStock: true },
    { id: "kp_013", sku: "CTR-GRN-EMERALD", name: "Emerald Pearl Granite", brand: "Castile Stone", category: "Countertop", style: "Classic", finish: "Polished", unitPrice: 95.00, unit: "sq ft", description: "Natural Brazilian emerald pearl granite, 3cm thick, polished", leadTimeDays: 7, inStock: true },
    { id: "kp_014", sku: "CTR-QTZ-MIDNIGHT", name: "Midnight Black Quartz", brand: "Castile Stone", category: "Countertop", style: "Contemporary", finish: "Matte", unitPrice: 92.00, unit: "sq ft", description: "Pure matte black quartz countertop, 3cm, industrial look", leadTimeDays: 10, inStock: true },
    { id: "kp_015", sku: "CTR-BUTCH-WALNUT", name: "Walnut Butcher Block", brand: "Castile Wood", category: "Countertop", style: "Rustic", finish: "Oil", unitPrice: 62.00, unit: "sq ft", description: "American walnut butcher block, 1.5 inch thick, food-safe oil finish", leadTimeDays: 7, inStock: true },
    // Hardware
    { id: "kp_016", sku: "HW-PULL-BRSH-BRZ", name: "Brushed Bronze Bar Pull 5\"", brand: "Atlas Homewares", category: "Hardware", style: "Modern", finish: "Brushed Bronze", unitPrice: 18.50, unit: "each", description: "5 inch center-to-center bar pull, brushed bronze finish", leadTimeDays: 3, inStock: true },
    { id: "kp_017", sku: "HW-PULL-MATTE-BLK", name: "Matte Black T-Bar Pull 7\"", brand: "Atlas Homewares", category: "Hardware", style: "Contemporary", finish: "Matte Black", unitPrice: 22.00, unit: "each", description: "7 inch center-to-center T-bar pull, matte black", leadTimeDays: 3, inStock: true },
    { id: "kp_018", sku: "HW-KNOB-CHROME", name: "Satin Nickel Round Knob", brand: "Atlas Homewares", category: "Hardware", style: "Classic", finish: "Satin Nickel", unitPrice: 8.75, unit: "each", description: "1.25 inch diameter round cabinet knob, satin nickel", leadTimeDays: 3, inStock: true },
    { id: "kp_019", sku: "HW-HINGE-SOFT", name: "Soft-Close Hinge Set", brand: "Blum", category: "Hardware", style: "Universal", finish: "Nickel", unitPrice: 12.00, unit: "set", description: "Blum clip-top soft-close hinge set, pair with mounting plate", leadTimeDays: 2, inStock: true },
    { id: "kp_020", sku: "HW-SLIDE-FULL-EXT", name: "Full-Extension Drawer Slide", brand: "Blum", category: "Hardware", style: "Universal", finish: "Zinc", unitPrice: 28.00, unit: "set", description: "Blum Tandem full-extension undermount drawer slide, soft-close", leadTimeDays: 2, inStock: true },
    // Accessories
    { id: "kp_021", sku: "ACC-TRASH-PULL", name: "30\" Trash Pull-Out", brand: "Rev-A-Shelf", category: "Accessory", style: "Universal", finish: "Chrome", unitPrice: 189.00, unit: "each", description: "30 inch two-bin trash and recycling pull-out for base cabinet", leadTimeDays: 5, inStock: true },
    { id: "kp_022", sku: "ACC-SPICE-PULL", name: "Spice Pull-Out Rack", brand: "Rev-A-Shelf", category: "Accessory", style: "Universal", finish: "Chrome", unitPrice: 145.00, unit: "each", description: "Full-extension spice rack pull-out for 11 inch base cabinet", leadTimeDays: 5, inStock: true },
    { id: "kp_023", sku: "ACC-LAZY-CORNER", name: "D-Shape Lazy Susan", brand: "Rev-A-Shelf", category: "Accessory", style: "Universal", finish: "Chrome", unitPrice: 215.00, unit: "each", description: "33 inch D-shape kidney lazy susan for corner cabinet", leadTimeDays: 5, inStock: true },
    { id: "kp_024", sku: "ACC-UNDERCAB-LIGHT", name: "Under-Cabinet LED Strip", brand: "Castile", category: "Accessory", style: "Universal", finish: "White", unitPrice: 45.00, unit: "linear ft", description: "Hardwired LED under-cabinet light strip, 2700K warm white, dimmable", leadTimeDays: 3, inStock: true },
    { id: "kp_025", sku: "ACC-CROWN-MOLD", name: "Crown Molding Kit", brand: "Castile Kitchens", category: "Accessory", style: "Traditional", finish: "Paintable", unitPrice: 18.00, unit: "linear ft", description: "Primed crown molding for cabinet-to-ceiling installation", leadTimeDays: 7, inStock: true },
];

export default kitchenProducts;
